/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        "primary-container": "#2e5bff",
        "on-secondary-container": "#616374",
        "on-tertiary-fixed-variant": "#004395",
        "surface-pure": "#FFFFFF",
        "secondary": "#5b5d6e",
        "primary-fixed": "#dde1ff",
        "on-secondary-fixed": "#181b29",
        "on-tertiary-container": "#edf0ff",
        "border-crisp": "#E2E8F0",
        "risk": "#D01E11",
        "outline-variant": "#c4c5d9",
        "on-surface": "#191c1e",
        "primary-fixed-dim": "#b8c3ff",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#0035be",
        "surface-container-high": "#F1F5F9",
        "tertiary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001356",
        "text-ink-primary": "#0F172A",
        "ai-surface-elevated": "#1E293B",
        "surface-container-low": "#F7F7F7",
        "on-secondary-fixed-variant": "#434655",
        "secondary-container": "#e0e1f5",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "inverse-primary": "#b8c3ff",
        "on-tertiary": "#ffffff",
        "error-container": "#FEF2F2",
        "on-tertiary-fixed": "#001a42",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#124af0",
        "on-error-container": "#991B1B",
        "on-secondary": "#ffffff",
        "text-ink-secondary": "#64748B",
        "tertiary": "#0051b0",
        "on-background": "#0F172A",
        "tertiary-container": "#0f69dc",
        "surface-dim": "#d8dadc",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#c4c5d8",
        "on-surface-variant": "#434656",
        "secondary-fixed": "#e0e1f5",
        "outline": "#94A3B8",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#efefff",
        "error": "#D01E11",
        surface: {
          DEFAULT: "var(--surface)",
          secondary: "var(--surface-secondary)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
        },
        border: {
          DEFAULT: "var(--border)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          hover: "var(--primary-hover)",
          soft: "var(--primary-soft)",
          foreground: "#FFFFFF",
        },
        success: {
          DEFAULT: "var(--success)",
          soft: "var(--success-soft)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          soft: "var(--warning-soft)",
        },
        danger: {
          DEFAULT: "var(--danger)",
          soft: "var(--danger-soft)",
        },
        info: {
          DEFAULT: "var(--info)",
          soft: "var(--info-soft)",
        },
        ai: {
          background: "var(--ai-background)",
          surface: "var(--ai-surface)",
          border: "var(--ai-border)",
          textPrimary: "var(--ai-text-primary)",
          textSecondary: "var(--ai-text-secondary)",
          "text-primary": "var(--ai-text-primary)",
          "text-secondary": "var(--ai-text-secondary)",
        },
      },
      spacing: {
        sm: "8px",
        unit: "4px",
        md: "12px",
        lg: "16px",
        xxl: "32px",
        xl: "24px",
        gutter: "16px",
        margin: "24px",
        xs: "4px",
      },
      borderRadius: {
        none: "0",
        sm: "4px",
        DEFAULT: "6px",
        md: "8px",
        lg: "12px",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["SFMono-Regular", "Roboto Mono", "Consolas", "monospace"],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "1.02", fontWeight: "600", letterSpacing: "-0.045em" }],
        "display-lg": ["32px", { lineHeight: "1.08", fontWeight: "600", letterSpacing: "-0.035em" }],
        "heading-lg": ["30px", { lineHeight: "38px", fontWeight: "600", letterSpacing: "-0.035em" }],
        "heading-md": ["17px", { lineHeight: "24px", fontWeight: "600", letterSpacing: "-0.015em" }],
        "body-lg": ["16px", { lineHeight: "25px", fontWeight: "400" }],
        "body": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-sm": ["13px", { lineHeight: "18px", fontWeight: "500", letterSpacing: "0.01em" }],
        "caption": ["11px", { lineHeight: "14px", fontWeight: "500", letterSpacing: "0.025em" }],
        "kpi-value": ["34px", { lineHeight: "40px", fontWeight: "600", letterSpacing: "-0.04em" }],
        "mono-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        subtle: "0 1px 2px 0 rgba(0, 0, 0, 0.03)",
        card: "0 2px 8px -2px rgba(17, 24, 39, 0.05), 0 4px 6px -1px rgba(17, 24, 39, 0.02)",
        drawer: "-4px 0 24px -4px rgba(17, 24, 39, 0.1)",
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        DEFAULT: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
      },
      transitionDuration: {
        fast: "150ms",
        normal: "200ms",
      }
    },
  },
  plugins: [],
};
