from fastapi import APIRouter
from app.api.v1.endpoints import health, score, graph, investigate, decision, policy, policies, stream, dashboard, simulation, audit, evaluation, transactions, investigations, settings, stripe_webhook, checkout_demo

api_router = APIRouter()
api_router.include_router(health.router, tags=["health"])
api_router.include_router(score.router, tags=["score"])
api_router.include_router(graph.router, tags=["graph"], prefix="/graph")
api_router.include_router(investigate.router, tags=["investigate"])
api_router.include_router(decision.router, tags=["decision"])
api_router.include_router(policy.router, tags=["policy"], prefix="/policy")
api_router.include_router(policies.router, tags=["policies"], prefix="/policies")
api_router.include_router(stream.router, tags=["stream"], prefix="/stream")
api_router.include_router(dashboard.router, tags=["dashboard"], prefix="/dashboard")
api_router.include_router(simulation.router, tags=["simulation"], prefix="/simulations")
api_router.include_router(audit.router, tags=["audit"], prefix="/audit")
api_router.include_router(evaluation.router, tags=["evaluation"], prefix="/evaluation")
api_router.include_router(transactions.router, tags=["transactions"], prefix="/transactions")
api_router.include_router(investigations.router, tags=["investigations"], prefix="/investigations")
api_router.include_router(settings.router, tags=["settings"], prefix="/settings")
api_router.include_router(stripe_webhook.router, tags=["stripe"], prefix="/stripe")
api_router.include_router(checkout_demo.router, tags=["checkout_demo"], prefix="/checkout")
