from enum import Enum

class LifecycleState(str, Enum):
    RECEIVED = "RECEIVED"
    PERSISTED = "PERSISTED"
    SCORED = "SCORED"
    GRAPH_CHECKED = "GRAPH_CHECKED"
    AGENT_SKIPPED = "AGENT_SKIPPED"
    INVESTIGATING = "INVESTIGATING"
    DECIDED = "DECIDED"
    AUDITED = "AUDITED"
    FAILED = "FAILED"
    DEGRADED = "DEGRADED"
