"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { fetchInvestigations } from "../../lib/api";
import { Search, SlidersHorizontal, ArrowRight } from "lucide-react";
import { ErrorState, EmptyState, Skeleton } from "../../components/ui";

export default function InvestigationsPage() {
  const [investigations, setInvestigations] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    loadData();
    const int = setInterval(loadData, 5000);
    return () => clearInterval(int);
  }, []);

  const loadData = async () => {
    setError(false);
    try {
      const data = await fetchInvestigations();
      setInvestigations(data.investigations || []);
    } catch (e) {
      console.error(e);
      setError(true);
    } finally {
      setLoading(false);
    }
  };

  const getSeverityBadge = (severity: string) => {
    switch (severity) {
      case "CRITICAL": return <span className="w-fit rounded-md border border-danger/20 bg-danger-soft px-2.5 py-1 text-caption font-semibold uppercase text-danger">CRITICAL</span>;
      case "HIGH": return <span className="w-fit rounded-md border border-warning/20 bg-warning-soft px-2.5 py-1 text-caption font-semibold uppercase text-warning">HIGH</span>;
      case "MEDIUM": return <span className="w-fit rounded-md border border-info/20 bg-info-soft px-2.5 py-1 text-caption font-semibold uppercase text-info">MEDIUM</span>;
      default: return <span className="w-fit rounded-md border border-border bg-surface-secondary px-2.5 py-1 text-caption font-semibold uppercase text-text-secondary">LOW</span>;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "OPEN": return <span className="px-2.5 py-1 text-caption font-semibold rounded-md uppercase bg-surface-secondary text-text-primary border border-border">OPEN</span>;
      case "INVESTIGATING": return <span className="w-fit rounded-md border border-primary/20 bg-primary-soft px-2.5 py-1 text-caption font-semibold uppercase text-primary">INVESTIGATING</span>;
      case "ESCALATED": return <span className="px-2.5 py-1 text-caption font-semibold rounded-md uppercase bg-warning-soft text-warning border border-warning/20">ESCALATED</span>;
      case "RESOLVED": return <span className="w-fit rounded-md border border-success/20 bg-success-soft px-2.5 py-1 text-caption font-semibold uppercase text-success">RESOLVED</span>;
      case "DISMISSED": return <span className="px-2.5 py-1 text-caption font-semibold rounded-md uppercase bg-surface-secondary text-text-muted border border-border border-dashed">DISMISSED</span>;
      default: return null;
    }
  };

  return (
    <div className="flex flex-col gap-8 pb-12 h-full">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex flex-col gap-1">
          <h1 className="text-heading-lg text-text-primary ">
            Investigations
          </h1>
          <p className="text-label-sm text-text-secondary font-medium">
            Manage fraud cases and alerts generated by the Risk Engine (seeded demo data).
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button className="bg-surface hover:bg-surface-secondary text-text-primary px-5 py-2.5 rounded-xl text-label-sm font-semibold transition-all border border-border shadow-sm flex items-center gap-2 opacity-75 cursor-not-allowed" disabled>
            Preview Export
          </button>
        </div>
      </div>

      <div className="bg-surface border border-border rounded-xl overflow-hidden shadow-sm flex flex-col h-full min-h-[600px]">
        
        <div className="p-5 border-b border-border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-surface-secondary/50">
          <div className="flex items-center gap-4">
            <button className="flex items-center gap-2 text-label-sm font-semibold text-text-secondary hover:text-text-primary px-4 py-2 rounded-lg border border-border bg-surface shadow-sm transition-colors">
              <SlidersHorizontal className="w-4 h-4" /> Filter
            </button>
            <span className="text-label-sm font-medium text-text-muted">{investigations.length} Cases Found</span>
          </div>
          <div className="relative w-full sm:w-72">
            <Search className="absolute left-3 h-4 w-4 text-text-muted pointer-events-none top-1/2 -translate-y-1/2" />
            <input 
              type="text" 
              placeholder="Search case ID or title..." 
              className="w-full bg-surface border border-border rounded-lg pl-10 pr-4 py-2 text-label-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/50 text-text-primary shadow-sm transition-all"
            />
          </div>
        </div>

        <div className="flex-1 overflow-x-auto">
          <table className="w-full text-left border-collapse whitespace-nowrap min-w-[1000px]">
            <thead className="bg-surface-secondary text-caption font-semibold uppercase text-text-muted border-b border-border">
              <tr>
                <th className="p-4 w-32">Case ID</th>
                <th className="p-4 w-64">Title / Trigger</th>
                <th className="p-4 w-32">Severity</th>
                <th className="p-4 w-24">Txns</th>
                <th className="p-4 w-32">Exposure</th>
                <th className="p-4 w-32">Assignee</th>
                <th className="p-4 w-36">Status</th>
                <th className="p-4 w-32">Created</th>
                <th className="p-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border bg-surface">
              {loading && <tr><td colSpan={9} className="px-6 py-12 text-center text-text-muted text-label-sm font-medium">Loading investigations...</td></tr>}
              {!loading && investigations.length === 0 && (
                <tr><td colSpan={9} className="px-6 py-12 text-center text-text-muted text-label-sm font-medium bg-surface-secondary/20">No open investigations found.</td></tr>
              )}
              {investigations.map(inv => (
                <tr key={inv.case_id} className="hover:bg-surface-secondary/50 transition-colors group">
                  <td className="p-4 whitespace-nowrap text-label-sm text-mono-sm font-mono font-semibold text-primary group-hover:underline cursor-pointer">{inv.case_id}</td>
                  <td className="p-4">
                    <div className="text-label-sm font-semibold text-text-primary mb-1 truncate max-w-xs" title={inv.title}>{inv.title}</div>
                    <div className="text-caption text-text-secondary truncate max-w-xs">{inv.trigger}</div>
                  </td>
                  <td className="p-4 whitespace-nowrap">{getSeverityBadge(inv.severity)}</td>
                  <td className="p-4 whitespace-nowrap text-label-sm text-mono-sm font-mono text-text-primary font-semibold">{inv.transactions?.length || 0}</td>
                  <td className="p-4 whitespace-nowrap text-label-sm text-mono-sm font-mono font-semibold text-danger tabular-nums">₹{(inv.exposure || 0).toLocaleString()}</td>
                  <td className="p-4 whitespace-nowrap">
                    <div className="flex items-center gap-2">
                      {inv.assignee ? (
                        <>
                          <div className="w-6 h-6 rounded-full bg-primary-soft text-primary flex items-center justify-center text-caption font-semibold">
                            {inv.assignee.split(' ').map((n: string) => n[0]).join('')}
                          </div>
                          <span className="text-label-sm font-medium text-text-primary">{inv.assignee}</span>
                        </>
                      ) : (
                        <span className="text-label-sm text-text-muted italic">Unassigned</span>
                      )}
                    </div>
                  </td>
                  <td className="p-4 whitespace-nowrap">{getStatusBadge(inv.status)}</td>
                  <td className="p-4 whitespace-nowrap text-caption text-mono-sm font-mono text-text-secondary">{new Date(inv.created_at).toLocaleString()}</td>
                  <td className="p-4 whitespace-nowrap text-right">
                    <Link href={`/investigations/${inv.case_id}`} className="inline-flex items-center gap-2 bg-primary text-white hover:bg-primary-hover px-4 py-2 rounded-lg text-caption font-semibold transition-all shadow-sm group-hover:premium-shadow-hover">
                      Investigate <ArrowRight className="w-3.5 h-3.5" />
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
