from enum import Enum

class DecisionType(str, Enum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"

class ReasonCode(str, Enum):
    VELOCITY_ANOMALY = "VELOCITY_ANOMALY"
    DEVICE_REUSE = "DEVICE_REUSE"
    IP_REUSE = "IP_REUSE"
    GRAPH_CLUSTER_RISK = "GRAPH_CLUSTER_RISK"
    UNUSUAL_AMOUNT = "UNUSUAL_AMOUNT"
    HIGH_ML_RISK = "HIGH_ML_RISK"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    AGENT_UNAVAILABLE = "AGENT_UNAVAILABLE"
